server:
  address: ${XMEX_SERVER_ADDRESS:0.0.0.0}
  port: ${XMEX_SERVER_PORT:80}
  ssl:
    enabled: ${XMEX_SERVER_SSL_ENABLED:off}
    key-store-type: ${XMEX_SERVER_SSL_KEY-STORE-TYPE:PKCS12}
    key-store: ${XMEX_SERVER_SSL_KEY_STORE:keystore}
    key-store-password: ${XMEX_SERVER_SSL_KEY_STORE_PASSWORD:changeIt}
  tomcat:
    max-keep-alive-requests: ${XMEX_SERVER_MAX_KEEP_ALIVE_REQUESTS:25}
    accesslog:
      enabled: ${XMEX_SERVER_ACCESS_LOG:off}
      buffered: off
      pattern: ${XMEX_SERVER_ACCESS_LOG_PATTERN:common}
      directory: ${XMEX_SERVER_ACCESS_LOG_DIRECTORY:}

storage:
  uri: ${XMEX_STORAGE_URI:/xmex!}
  directory: ${XMEX_STORAGE_DIRECTORY:./data}
  space: ${XMEX_STORAGE_SPACE:256K}
  quantity: ${XMEX_STORAGE_QUANTITY:65535}
  expiration: ${XMEX_STORAGE_EXPIRATION:900s}

acme:
  port: ${XMEX_ACME_PORT:80}
  hash: ${XMEX_ACME_HASH:}
  token:
    uri: ${XMEX_ACME_TOKEN_URI:}

content:
  directory: ${XMEX_CONTENT_DIRECTORY:./content}
  default: ${XMEX_CONTENT_DEFAULT:index.htm index.html index.xhtml}
