server:
  address: ${XMEX_SERVER_ADDRESS:0.0.0.0}
  port: ${XMEX_SERVER_PORT:80}
  ssl:
    enabled: ${XMEX_SERVER_SSL_ENABLED:off}
    key-store-type: ${XMEX_SERVER_SSL_KEY-STORE-TYPE:PKCS12}
    key-store: ${XMEX_SERVER_SSL_KEY_STORE:keystore}
    key-store-password: ${XMEX_SERVER_SSL_KEY_STORE_PASSWORD:changeIt}
  tomcat:
    max-keep-alive-requests: ${XMEX_SERVER_MAX_KEEP_ALIVE_REQUESTS:25}

acme:
  port: ${XMEX_ACME_PORT:80}
  hash: ${XMEX_ACME_HASH:}
  token:
    uri: ${XMEX_ACME_TOKEN_URI:}

datasource:
  directory: ${XMEX_DATASOURCE_DIRECTORY:./data}
  service:
    uri: ${XMEX_datasource_SERVICE_URI:/xmex!}

content:
  directory: ${XMEX_CONTENT_DIRECTORY:./content}
  default: ${XMEX_CONTENT_DEFAULT:index.htm index.html index.xhtml}
